INSERT INTO CLIENT(ID, NOM, MONTANT_COMPTE) VALUES ('1', 'BEIRAO', 1000);
INSERT INTO CLIENT(ID, NOM, MONTANT_COMPTE) VALUES ('2', 'BOUCHE', 0);
INSERT INTO CLIENT(ID, NOM, MONTANT_COMPTE) VALUES ('3', 'COSSIN', 12);
INSERT INTO CLIENT(ID, NOM, MONTANT_COMPTE) VALUES ('4', 'BARTHELEMY', 200);
